version: '3.5'
services:
  lumen-book:
    image: docker.pkg.github.com/marcware/gha-devops-backend/geekshubs-library_app:${TAG}
    container_name: lumen-book
    ports:
      - 80:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      - app-lumen-network

networks:
  app-lumen-network:
    driver: "bridge"
