name: build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: "web1.marcware.es"
          username: "root"
          #password: "635c829773a2dMarta"
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiGkto4bVQhI/IBPo0gC4gZejs0uK8gLBFtmWJyKjDj2jBgW49K0XYluAsR9ogBO613+MHsSYVi+UKN1xlFbXh+qeuiWRSrJ8YLuIH0GSKjLcBUCGex5U/vkDG+qkRu79AuPzzT1ybZ/46Rz23mFUSxTxgLD6TI3rPKi5fMY3me9NvXZLw2ozdSvs089taRcRru/gKDpwO3VqvVxFkPq5qkbJan9nPfSap2FRnyxkc6XsDFYe7HKjc4IjJ5rNWUi9QE9015F0LeD6KcBw+QFEujaRvK77eMDJHm+GGtLAyAMmzGDb+OVTbT4cXodv/qJ7xJbQor34Eff/pNS8mcbWX marcware@PROX15"
          port: "22"
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            whoami
            ls -al
         # script: |
          #  docker stop $(docker ps -a -q)
          #  docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
          #  docker pull docker.pkg.github.com/marcware/gha-devops-backend/books_app:latest
          #  docker run -dit -p 80:80 docker.pkg.github.com/marcware/gha-devops-backend/books_app:latest