name: build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_PRIVATE }}
          port: ${{ secrets.PORT }}
          script: |
            cd GHA-DevOps-Backend
            docker-compose down
            git fetch --all
            git reset --hard origin/main
            docker pull marcware/books_app:lastest
            docker-compose -f docker-compose-prod.yml up
            docker exec -it lumen-book composer install
            cp .env.pro .env
            chmod -R ug+rwx storage bootstrap/cache vendor

