name: build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_PRIVATE }}
          port: ${{ secrets.PORT }}
          script: |
            docker-compose down
            git fetch --all
            git reset --hard origin/main
            docker pull marcware/books_app:lastest
            docker-compose docker-compose-prod.yml up -d