name: ci/cd workflow

on:
  push:
    branches:
      - develop
      - features/*
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1]

    name: Test - PHP ${{ matrix.php }}

    steps:
      - name: Copy Repo Files
        uses: actions/checkout@master
      - name: Build the stack
        run: ls -la
      - name: Test
        run: make docker-tests

  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          #password: ${{ secrets.GITHUB_TOKEN }}
          password: "c57bb3e99719fe63c65f3af0f799753b4807abe5"
          registry: docker.pkg.github.com
          repository: marcware/gha-devops-backend/books_app
          tag_with_ref: true
