name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Laravel
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Tag
        uses: ChloePlanet/github-tag-action@master
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main

      - name: Publish Docker Image
        if: ${{ steps.tag.outputs.tag_generated == 1 }}
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: 'geekshubs-library_app'
          TAG: ${{ steps.tag.outputs.new_tag }}
          DOCKERFILE_PATH: 'Dockerfile'
          BUILD_CONTEXT: '.'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          name: id_rsa.pub
          key: ${{ secrets.KEY_PUBLIC }}
          known_hosts: ${{ secrets.KNOWN_HOST }}


      - name: SSH key list
        run: |
          cd ~/.ssh
          ls -la



      - name: Deploy docker-compose-prod
        if: ${{ steps.tag.outputs.tag_generated == 1 }}
        run: |
            COMPOSE_HTTP_TIMEOUT=120 TAG=${{ steps.tag.outputs.new_tag }} docker-compose --context remote -f docker-compose-prod.yml pull app
            COMPOSE_HTTP_TIMEOUT=120 TAG=${{ steps.tag.outputs.new_tag }} docker-compose --context remote -f docker-compose-prod.yml up -d app


